### ISSUE TITLE
NameError: name 'BinaryViewType' is not defined

### ISSUE THREAD

**Issue by bmuessig** [cah011/binja-avr#15]
I am using BN Version 1.1.1555 Personal.
When launching BN, this error is thrown:
```
Traceback (most recent call last):
  File "~/.binaryninja/plugins/binja-avr/__init__.py", line 1191, in <module>
    BinaryViewType['ELF'].register_arch(83, Endianness.LittleEndian, Architecture["AVR"])
NameError: name 'BinaryViewType' is not defined
Python plugin 'binja-avr' could not be loaded
```

**Comment by bmuessig** [comment]
I have now added the following to `__init__.py`:
```
from binaryninja.binaryview import BinaryViewType
from binaryninja.enums import Endianness
```

This results in an internal error of the BN API itself:

```
Traceback (most recent call last):
  File "/opt/binaryninja/plugins/../python/binaryninja/architecture.py", line 890, in _get_stack_pointer_register
    return self._all_regs[self.stack_pointer]
KeyError: 'SP'
Loaded Python plugin 'binja-avr'
```

**Comment by Knight-Ops** [comment]
This is likely due to API changes within Binary Ninja. They may have
changed how the disassemblers get certain registers. I don't have any AVR
binaries available to test on currently, but I will try to look at the API
changes soon.
